sig-release:
    sig-release-1.10-all:
        ci-kubernetes-e2e-gce-cos-k8sstable3-default:
        - 498
    sig-release-1.11-all:
        ci-kubernetes-e2e-gce-cos-k8sstable2-default:
        - 1978
    sig-release-1.12-all:
        ci-kubernetes-e2e-gce-cos-k8sstable1-default:
        - 5860
    sig-release-1.13-all:
        ci-kubernetes-e2e-gce-cos-k8sbeta-default:
        - 9957
    sig-release-master-blocking:
        ci-kubernetes-e2e-gci-gce:
        - 35851
